<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>detail_gist_extension</name>
   <tag></tag>
   <elementGuidId>e3858b03-b41e-4edb-a165-c469db4f10c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;gist-pjax-container&quot;]/div[1]/div/div[1]/h1/strong/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;gist-pjax-container&quot;]/div[1]/div/div[1]/h1/strong/a</value>
   </webElementProperties>
</WebElementEntity>
